services:
  - type: web
    name: linha-do-tempo
    runtime: docker
    dockerfilePath: Dockerfile
    buildCommand: docker build -t linha-do-tempo .
    startCommand: docker run -p ${PORT}:${PORT} linha-do-tempo
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: linha-do-tempo
          property: host
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: PORT
        value: "8080"
      - key: APACHE_LOG_DIR
        value: "/var/log/apache2" 