services:
  - type: web
    name: linha-do-tempo
    runtime: docker
    region: oregon
    plan: starter
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Linha do Tempo"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: 35.227.164.209
      - key: DB_PORT
        value: "6432"
      - key: DB_DATABASE
        value: linha_do_tempo
      - key: DB_USERNAME
        value: linha_do_tempo_user
      - key: DB_PASSWORD
        value: 455z58jML513WywHYCqLgsWHtPf40b11
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DRIVER
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: "120"
      - key: PORT
        value: "8080"
      - key: APACHE_LOG_DIR
        value: "/var/log/apache2" 